basePath: /api
definitions:
  models.Employee:
    properties:
      age:
        type: integer
      id:
        type: integer
      name:
        type: string
      position:
        type: string
    type: object
  models.EmployeeProjectsResponse:
    properties:
      employee:
        $ref: '#/definitions/models.Employee'
      projects:
        items:
          $ref: '#/definitions/models.Project'
        type: array
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.Project:
    properties:
      description:
        type: string
      employee_id:
        type: integer
      id:
        type: integer
      name:
        type: string
    type: object
host: localhost:5000
info:
  contact: {}
  description: API for managing employees
  title: Employee Project Management Service API
  version: "1.0"
paths:
  /employees/{id}/projects:
    get:
      consumes:
      - application/json
      description: Get employee data and related projects
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.EmployeeProjectsResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get employee projects
      tags:
      - employees
swagger: "2.0"
